// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxoySlSE3636tYkA0KIW9s76Nyl_1XKgA',
    appId: '1:1010720226046:web:4e4bf2848ab2753224c3af',
    messagingSenderId: '1010720226046',
    projectId: 'guardians-eye',
    authDomain: 'guardians-eye.firebaseapp.com',
    storageBucket: 'guardians-eye.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHgv-uj-6kZc1cXq4hXlj9aQo9nzepD1o',
    appId: '1:1010720226046:android:d58ef515038c1a9a24c3af',
    messagingSenderId: '1010720226046',
    projectId: 'guardians-eye',
    storageBucket: 'guardians-eye.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2221YhqJGe_Gwh3JvPJWCSvaXf190KXM',
    appId: '1:1010720226046:ios:14ff104d9afa64a824c3af',
    messagingSenderId: '1010720226046',
    projectId: 'guardians-eye',
    storageBucket: 'guardians-eye.appspot.com',
    iosBundleId: 'com.example.guardiansEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2221YhqJGe_Gwh3JvPJWCSvaXf190KXM',
    appId: '1:1010720226046:ios:ffe9aeb98962931024c3af',
    messagingSenderId: '1010720226046',
    projectId: 'guardians-eye',
    storageBucket: 'guardians-eye.appspot.com',
    iosBundleId: 'com.example.guardiansEye.RunnerTests',
  );
}
