// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Tfesn9uf4Ua9azgen-q5s8FSXtkAzGY',
    appId: '1:467218372665:web:8444386d89592b3ad295e8',
    messagingSenderId: '467218372665',
    projectId: 'gaurdianeye-cc53a',
    authDomain: 'gaurdianeye-cc53a.firebaseapp.com',
    storageBucket: 'gaurdianeye-cc53a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCJHXAbfWzj5R2zrW8YkMxY4TxZRArt0w',
    appId: '1:467218372665:android:591a1693504a9919d295e8',
    messagingSenderId: '467218372665',
    projectId: 'gaurdianeye-cc53a',
    storageBucket: 'gaurdianeye-cc53a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2cIN08BOrmv9rEE23oM3w2LOUiqwxAh4',
    appId: '1:467218372665:ios:a7117743d99f4950d295e8',
    messagingSenderId: '467218372665',
    projectId: 'gaurdianeye-cc53a',
    storageBucket: 'gaurdianeye-cc53a.firebasestorage.app',
    iosBundleId: 'com.example.guardiansEye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2cIN08BOrmv9rEE23oM3w2LOUiqwxAh4',
    appId: '1:467218372665:ios:a7117743d99f4950d295e8',
    messagingSenderId: '467218372665',
    projectId: 'gaurdianeye-cc53a',
    storageBucket: 'gaurdianeye-cc53a.firebasestorage.app',
    iosBundleId: 'com.example.guardiansEye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7Tfesn9uf4Ua9azgen-q5s8FSXtkAzGY',
    appId: '1:467218372665:web:df2c9f061b739b6ad295e8',
    messagingSenderId: '467218372665',
    projectId: 'gaurdianeye-cc53a',
    authDomain: 'gaurdianeye-cc53a.firebaseapp.com',
    storageBucket: 'gaurdianeye-cc53a.firebasestorage.app',
  );

}